<?php

/**
 * This is the model base class for the table "tb_Consumo_Energia".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbConsumoEnergia".
 *
 * Columns in table "tb_Consumo_Energia" available as properties of the model,
 * followed by relations of table "tb_Consumo_Energia" available as properties of the model.
 *
 * @property integer $id_Consumo_Energia
 * @property integer $id_Balance
 * @property integer $Cantidad
 * @property string $Detalle
 * @property double $Kv_por_Hora
 * @property double $Total
 *
 * @property TbBalance $idBalance
 */
abstract class BaseTbConsumoEnergia extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tb_Consumo_Energia';
    }

    public static function representingColumn() {
        return 'Detalle';
    }
     public function TotalTotal($records)
    {
            $Totalt=0;
            foreach($records as $record)
                    $Totalt+=$record->Total;
            return $Totalt;
    }   

    public function rules() {
        return array(
            array('id_Balance, Detalle', 'required'),
            array('id_Balance, Cantidad', 'numerical', 'integerOnly'=>true),
            array('Kv_por_Hora, Total', 'numerical'),
            array('Detalle', 'length', 'max'=>50),
            array('Cantidad, Kv_por_Hora, Total', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_Consumo_Energia, id_Balance, Cantidad, Detalle, Kv_por_Hora, Total', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'idBalance' => array(self::BELONGS_TO, 'TbBalance', 'id_Balance'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_Consumo_Energia' => Yii::t('app', 'Id consumo energia'),
                'id_Balance' => Yii::t('app', 'Balance para la producción de:'),
                'Cantidad' => Yii::t('app', 'Cantidad'),
                'Detalle' => Yii::t('app', 'Detalle'),
                'Kv_por_Hora' => Yii::t('app', 'Kv por hora'),
                'Total' => Yii::t('app', 'Total'),
                'idBalance' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_Consumo_Energia', $this->id_Consumo_Energia);
        $criteria->compare('id_Balance', $this->id_Balance);
        $criteria->compare('Cantidad', $this->Cantidad);
        $criteria->compare('Detalle', $this->Detalle, true);
        $criteria->compare('Kv_por_Hora', $this->Kv_por_Hora);
        $criteria->compare('Total', $this->Total);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}