<?php

/**
 * This is the model base class for the table "tb_Balance".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbBalance".
 *
 * Columns in table "tb_Balance" available as properties of the model,
 * followed by relations of table "tb_Balance" available as properties of the model.
 *
 * @property integer $id_Balance
 * @property string $Producto
 * @property integer $Capacidad_maquina
 * @property integer $Paradas
 * @property integer $Dias_al_mes
 * @property double $Malanga_pesada_Kg
 * @property integer $Malanga_pesada_pP
 * @property double $Malanga_pesada_pKg
 * @property double $Lavado_y_pelado_Kg
 * @property integer $Lavado_y_pelado_pP
 * @property double $Lavado_y_pelado_pKg
 * @property double $Rebanado_Kg
 * @property integer $Rebanado_pP
 * @property double $Rebanado_pKg
 * @property double $Freir_Kg
 * @property integer $Freir_pP
 * @property double $Freir_pKg
 * @property double $Enfriar_Kg
 * @property integer $Enfriar_pP
 * @property double $Enfriar_pKg
 * @property double $Condimentar_kg
 * @property integer $Condimentar_pP
 * @property string $Condimentar_pKg
 * @property double $Empacar_Kg
 * @property integer $Empacar_pP
 * @property double $Empacar_pKg
 * @property double $Almacenar_Kg
 * @property integer $Almacenar_pKg
 * @property integer $Almacenar_pP
 * @property double $Total_Kg
 * @property integer $Total_pP
 * @property double $Total_pKg
 *
 * @property TbConsumoEnergia[] $tbConsumoEnergias
 * @property TbProduccion[] $tbProduccions
 */
abstract class BaseTbBalance extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tb_Balance';
    }

    public static function representingColumn() {
        return 'Producto';
    }

    public function rules() {
        return array(
            array('Producto', 'required'),
            array('Capacidad_maquina, Paradas, Dias_al_mes, ', 'numerical', 'integerOnly'=>true),
            array('Malanga_pesada_Kg, Malanga_pesada_pKg, Lavado_y_pelado_Kg, Lavado_y_pelado_pKg, Rebanado_Kg, Rebanado_pKg, Freir_Kg, Freir_pKg, Enfriar_Kg, Enfriar_pKg, Condimentar_kg, Empacar_Kg, Empacar_pKg, Almacenar_Kg, Total_Kg, Total_pKg,Malanga_pesada_pP, Lavado_y_pelado_pP, Rebanado_pP, Freir_pP, Enfriar_pP, Condimentar_pP, Empacar_pP, Almacenar_pP, Almacenar_pKg, Total_pP', 'numerical'),
            array('Producto', 'length', 'max'=>100),
            array('Condimentar_pKg', 'length', 'max'=>45),
            array('Capacidad_maquina, Paradas, Dias_al_mes, Malanga_pesada_Kg, Malanga_pesada_pP, Malanga_pesada_pKg, Lavado_y_pelado_Kg, Lavado_y_pelado_pP, Lavado_y_pelado_pKg, Rebanado_Kg, Rebanado_pP, Rebanado_pKg, Freir_Kg, Freir_pP, Freir_pKg, Enfriar_Kg, Enfriar_pP, Enfriar_pKg, Condimentar_kg, Condimentar_pP, Condimentar_pKg, Empacar_Kg, Empacar_pP, Empacar_pKg, Almacenar_Kg, Almacenar_pP, Almacenar_pKg, Total_Kg, Total_pP, Total_pKg', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_Balance, Producto, Capacidad_maquina, Paradas, Dias_al_mes, Malanga_pesada_Kg, Malanga_pesada_pP, Malanga_pesada_pKg, Lavado_y_pelado_Kg, Lavado_y_pelado_pP, Lavado_y_pelado_pKg, Rebanado_Kg, Rebanado_pP, Rebanado_pKg, Freir_Kg, Freir_pP, Freir_pKg, Enfriar_Kg, Enfriar_pP, Enfriar_pKg, Condimentar_kg, Condimentar_pP, Condimentar_pKg, Empacar_Kg, Empacar_pP, Empacar_pKg, Almacenar_Kg, Almacenar_pP, Almacenar_pKg, Total_Kg, Total_pP, Total_pKg', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'tbConsumoEnergias' => array(self::HAS_MANY, 'TbConsumoEnergia', 'id_Balance'),
            'tbProduccions' => array(self::HAS_MANY, 'TbProduccion', 'id_Balance'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_Balance' => Yii::t('app', 'Id Balance'),
                'Producto' => Yii::t('app', 'Producto'),
                'Capacidad_maquina' => Yii::t('app', 'Capacidad Maquina'),
                'Paradas' => Yii::t('app', 'Paradas'),
                'Dias_al_mes' => Yii::t('app', 'Dias Al Mes'),
                'Malanga_pesada_Kg' => Yii::t('app', 'Malanga Pesada Kg'),
                'Malanga_pesada_pP' => Yii::t('app', 'Malanga Pesada P P'),
                'Malanga_pesada_pKg' => Yii::t('app', 'Malanga Pesada P Kg'),
                'Lavado_y_pelado_Kg' => Yii::t('app', 'Lavado Y Pelado Kg'),
                'Lavado_y_pelado_pP' => Yii::t('app', 'Lavado Y Pelado P P'),
                'Lavado_y_pelado_pKg' => Yii::t('app', 'Lavado Y Pelado P Kg'),
                'Rebanado_Kg' => Yii::t('app', 'Rebanado Kg'),
                'Rebanado_pP' => Yii::t('app', 'Rebanado P P'),
                'Rebanado_pKg' => Yii::t('app', 'Rebanado P Kg'),
                'Freir_Kg' => Yii::t('app', 'Freir Kg'),
                'Freir_pP' => Yii::t('app', 'Freir P P'),
                'Freir_pKg' => Yii::t('app', 'Freir P Kg'),
                'Enfriar_Kg' => Yii::t('app', 'Enfriar Kg'),
                'Enfriar_pP' => Yii::t('app', 'Enfriar P P'),
                'Enfriar_pKg' => Yii::t('app', 'Enfriar P Kg'),
                'Condimentar_kg' => Yii::t('app', 'Condimentar Kg'),
                'Condimentar_pP' => Yii::t('app', 'Condimentar P P'),
                'Condimentar_pKg' => Yii::t('app', 'Condimentar P Kg'),
                'Empacar_Kg' => Yii::t('app', 'Empacar Kg'),
                'Empacar_pP' => Yii::t('app', 'Empacar P P'),
                'Empacar_pKg' => Yii::t('app', 'Empacar P Kg'),
                'Almacenar_Kg' => Yii::t('app', 'Almacenar Kg'), 
                'Almacenar_pP' => Yii::t('app', 'Almacenar P P'),
            'Almacenar_pKg' => Yii::t('app', 'Almacenar P Kg'),
                'Total_Kg' => Yii::t('app', 'Total Kg'),
                'Total_pP' => Yii::t('app', 'Total P P'),
                'Total_pKg' => Yii::t('app', 'Total P Kg'),
                'tbConsumoEnergias' => null,
                'tbProduccions' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_Balance', $this->id_Balance);
        $criteria->compare('Producto', $this->Producto, true);
        $criteria->compare('Capacidad_maquina', $this->Capacidad_maquina);
        $criteria->compare('Paradas', $this->Paradas);
        $criteria->compare('Dias_al_mes', $this->Dias_al_mes);
        $criteria->compare('Malanga_pesada_Kg', $this->Malanga_pesada_Kg);
        $criteria->compare('Malanga_pesada_pP', $this->Malanga_pesada_pP);
        $criteria->compare('Malanga_pesada_pKg', $this->Malanga_pesada_pKg);
        $criteria->compare('Lavado_y_pelado_Kg', $this->Lavado_y_pelado_Kg);
        $criteria->compare('Lavado_y_pelado_pP', $this->Lavado_y_pelado_pP);
        $criteria->compare('Lavado_y_pelado_pKg', $this->Lavado_y_pelado_pKg);
        $criteria->compare('Rebanado_Kg', $this->Rebanado_Kg);
        $criteria->compare('Rebanado_pP', $this->Rebanado_pP);
        $criteria->compare('Rebanado_pKg', $this->Rebanado_pKg);
        $criteria->compare('Freir_Kg', $this->Freir_Kg);
        $criteria->compare('Freir_pP', $this->Freir_pP);
        $criteria->compare('Freir_pKg', $this->Freir_pKg);
        $criteria->compare('Enfriar_Kg', $this->Enfriar_Kg);
        $criteria->compare('Enfriar_pP', $this->Enfriar_pP);
        $criteria->compare('Enfriar_pKg', $this->Enfriar_pKg);
        $criteria->compare('Condimentar_kg', $this->Condimentar_kg);
        $criteria->compare('Condimentar_pP', $this->Condimentar_pP);
        $criteria->compare('Condimentar_pKg', $this->Condimentar_pKg, true);
        $criteria->compare('Empacar_Kg', $this->Empacar_Kg);
        $criteria->compare('Empacar_pP', $this->Empacar_pP);
        $criteria->compare('Empacar_pKg', $this->Empacar_pKg);
        $criteria->compare('Almacenar_Kg', $this->Almacenar_Kg); 
        $criteria->compare('Almacenar_pP', $this->Almacenar_pP);
        $criteria->compare('Almacenar_pKg', $this->Almacenar_pKg);
        $criteria->compare('Total_Kg', $this->Total_Kg);
        $criteria->compare('Total_pP', $this->Total_pP);
        $criteria->compare('Total_pKg', $this->Total_pKg);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}