<?php

/**
 * This is the model base class for the table "tb_Gastos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbGastos".
 *
 * Columns in table "tb_Gastos" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_Gastos
 * @property string $Gasto
 * @property double $Al_mes
 * @property integer $Cantidad_meses
 * @property double $Total
 *
 */
abstract class BaseTbGastos extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tb_Gastos';
    }

    public static function representingColumn() {
        return 'Gasto';
    }

         public function TotalTotal($records)
    {
            $Totalt=0;
            foreach($records as $record)
                    $Totalt+=$record->Total;
            return $Totalt;
    }   
    public function rules() {
        return array(
            array('Gasto, Al_mes', 'required'),
            array('Cantidad_meses', 'numerical', 'integerOnly'=>true),
            array('Al_mes, Total', 'numerical'),
            array('Gasto', 'length', 'max'=>45),
            array('Cantidad_meses, Total', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_Gastos, Gasto, Al_mes, Cantidad_meses, Total', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_Gastos' => Yii::t('app', 'Id Gastos'),
                'Gasto' => Yii::t('app', 'Gasto'),
                'Al_mes' => Yii::t('app', 'Al Mes'),
                'Cantidad_meses' => Yii::t('app', 'Cantidad Meses'),
                'Total' => Yii::t('app', 'Total'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_Gastos', $this->id_Gastos);
        $criteria->compare('Gasto', $this->Gasto, true);
        $criteria->compare('Al_mes', $this->Al_mes);
        $criteria->compare('Cantidad_meses', $this->Cantidad_meses);
        $criteria->compare('Total', $this->Total);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}