<?php

/**
 * This is the model base class for the table "tb_SBasico".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbSBasico".
 *
 * Columns in table "tb_SBasico" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_SBasico
 * @property string $Servicio_Basico
 * @property integer $Capacidad
 * @property double $Precio
 * @property double $Total
 * @property string $Descripcion
 *
 */
abstract class BaseTbSBasico extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tb_SBasico';
    }

    public static function representingColumn() {
        return 'Servicio_Basico';
    }

    public function rules() {
        return array(
            array('Capacidad', 'numerical', 'integerOnly'=>true),
            array('Precio, Total', 'numerical'),
            array('Servicio_Basico', 'length', 'max'=>100),
            array('Descripcion', 'length', 'max'=>200),
            array('Servicio_Basico, Capacidad, Precio, Total, Descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_SBasico, Servicio_Basico, Capacidad, Precio, Total, Descripcion', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_SBasico' => Yii::t('app', 'Id Sbasico'),
                'Servicio_Basico' => Yii::t('app', 'Servicio Basico'),
                'Capacidad' => Yii::t('app', 'Capacidad'),
                'Precio' => Yii::t('app', 'Precio'),
                'Total' => Yii::t('app', 'Total'),
                'Descripcion' => Yii::t('app', 'Descripcion'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_SBasico', $this->id_SBasico);
        $criteria->compare('Servicio_Basico', $this->Servicio_Basico, true);
        $criteria->compare('Capacidad', $this->Capacidad);
        $criteria->compare('Precio', $this->Precio);
        $criteria->compare('Total', $this->Total);
        $criteria->compare('Descripcion', $this->Descripcion, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}