<?php

/**
 * This is the model base class for the table "tb_MateriaPrima".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbMateriaPrima".
 *
 * Columns in table "tb_MateriaPrima" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_MateriaPrima
 * @property integer $id_Balance
 * @property string $Materia_Prima_e_Insumos
 * @property integer $Capacidad_mes
 * @property double $Precio
 * @property double $Total
 *
 * @property TbBalance $idBalance
 */
abstract class BaseTbMateriaPrima extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tb_MateriaPrima';
    }

    public static function representingColumn() {
        return 'Materia_Prima_e_Insumos';
    }

        public function TotalTotal($records)
    {
            $Totalt=0;
            foreach($records as $record)
                    $Totalt+=$record->Total;
            return $Totalt;
    }   
    public function rules() {
        return array(
            array('id_Balance, Materia_Prima_e_Insumos', 'required'),
            array('id_Balance, Capacidad_mes', 'numerical', 'integerOnly'=>true),
            array('Precio, Total', 'numerical'),
            array('Materia_Prima_e_Insumos', 'length', 'max'=>75),
            array('Capacidad_mes, Precio, Total', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_MateriaPrima, id_Balance, Materia_Prima_e_Insumos, Capacidad_mes, Precio, Total', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
             'idBalance' => array(self::BELONGS_TO, 'TbBalance', 'id_Balance'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_MateriaPrima' => Yii::t('app', 'Id materia prima'),
                'id_Balance' => Yii::t('app', 'Balance para la producción de:'),
                'Materia_Prima_e_Insumos' => Yii::t('app', 'Materia prima E insumos'),
                'Capacidad_mes' => Yii::t('app', 'Capacidad al mes'),
                'Precio' => Yii::t('app', 'Precio'),
                'Total' => Yii::t('app', 'Total'),
                'idBalance' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_MateriaPrima', $this->id_MateriaPrima);
        $criteria->compare('id_Balance', $this->id_Balance);
        $criteria->compare('Materia_Prima_e_Insumos', $this->Materia_Prima_e_Insumos, true);
        $criteria->compare('Capacidad_mes', $this->Capacidad_mes);
        $criteria->compare('Precio', $this->Precio);
        $criteria->compare('Total', $this->Total);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}