<?php

/**
 * This is the model base class for the table "tb_PMPSemanal".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbPMPSemanal".
 *
 * Columns in table "tb_PMPSemanal" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_PMPSemanal
 * @property integer $id_Produccion
 * @property string $Mes
 * @property integer $S1
 * @property integer $S2
 * @property integer $S3
 * @property integer $S4
 * @property integer $Total_Produccion
 * @property integer $Estandar_Produccion
 * @property integer $Porcentaje
 * @property double $Produciendo_Planta
 *
 */
abstract class BaseTbPMPSemanal extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tb_PMPSemanal';
    }

    public static function representingColumn() {
        return 'Mes';
    }

    public function rules() {
        return array(
            array('id_Produccion, S1, S2, S3, S4, Total_Produccion, Estandar_Produccion', 'numerical', 'integerOnly'=>true),
            array('Produciendo_Planta, Porcentaje', 'numerical'),
            array('Mes', 'length', 'max'=>20),
            array('id_Produccion, Mes, S1, S2, S3, S4, Total_Produccion, Estandar_Produccion, Porcentaje, Produciendo_Planta', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_PMPSemanal, id_Produccion, Mes, S1, S2, S3, S4, Total_Produccion, Estandar_Produccion, Porcentaje, Produciendo_Planta', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
             'idProduccion' => array(self::BELONGS_TO, 'TbProduccion', 'id_Produccion'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_PMPSemanal' => Yii::t('app', 'Id PMP semanal'),
                'id_Produccion' => Yii::t('app', 'Id Produccion'),
                'Mes' => Yii::t('app', 'Mes'),
                'S1' => Yii::t('app', '1ra. Semana'),
                'S2' => Yii::t('app', '2da. Semana'),
                'S3' => Yii::t('app', '3ra. Semana'),
                'S4' => Yii::t('app', '4ta. Semana'),
                'Total_Produccion' => Yii::t('app', 'Total Produccion'),
                'Estandar_Produccion' => Yii::t('app', 'Estandar Produccion'),
                'Porcentaje' => Yii::t('app', 'Porcentaje'),
                'Produciendo_Planta' => Yii::t('app', 'Produciendo Planta'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_PMPSemanal', $this->id_PMPSemanal);
        $criteria->compare('id_Produccion', $this->id_Produccion);
        $criteria->compare('Mes', $this->Mes, true);        
        $criteria->compare('S1', $this->S1);
        $criteria->compare('S2', $this->S2);
        $criteria->compare('S3', $this->S3);
        $criteria->compare('S4', $this->S4);
        $criteria->compare('Total_Produccion', $this->Total_Produccion);
        $criteria->compare('Estandar_Produccion', $this->Estandar_Produccion);
        $criteria->compare('Porcentaje', $this->Porcentaje);
        $criteria->compare('Produciendo_Planta', $this->Produciendo_Planta);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}