<?php

/**
 * This is the model base class for the table "tb_Maquinaria_Equipo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbMaquinariaEquipo".
 *
 * Columns in table "tb_Maquinaria_Equipo" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_Maquinaria_Equipo
 * @property string $Maquinaria_o_Equipo
 * @property integer $Cantidad
 * @property double $Precio_Unitario
 * @property double $Total
 *
 */
abstract class BaseTbMaquinariaEquipo extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tb_Maquinaria_Equipo';
    }

    public static function representingColumn() {
        return 'Maquinaria_o_Equipo';
    }

    public function TotalTotal($records)
    {
            $Totalt=0;
            foreach($records as $record)
                    $Totalt+=$record->Total;
            return $Totalt;
    }                                                       
    public function rules() {
        return array(
            array('Maquinaria_o_Equipo, Cantidad', 'required'),
            array('Cantidad', 'numerical', 'integerOnly'=>true),
            array('Precio_Unitario, Total', 'numerical'),
            array('Maquinaria_o_Equipo', 'length', 'max'=>75),
            array('Precio_Unitario, Total', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_Maquinaria_Equipo, Maquinaria_o_Equipo, Cantidad, Precio_Unitario, Total', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_Maquinaria_Equipo' => Yii::t('app', 'Id Maquinaria Equipo'),
                'Maquinaria_o_Equipo' => Yii::t('app', 'Maquinaria O Equipo'),
                'Cantidad' => Yii::t('app', 'Cantidad'),
                'Precio_Unitario' => Yii::t('app', 'Precio Unitario'),
                'Total' => Yii::t('app', 'Total'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_Maquinaria_Equipo', $this->id_Maquinaria_Equipo);
        $criteria->compare('Maquinaria_o_Equipo', $this->Maquinaria_o_Equipo, true);
        $criteria->compare('Cantidad', $this->Cantidad);
        $criteria->compare('Precio_Unitario', $this->Precio_Unitario);
        $criteria->compare('Total', $this->Total);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}