<?php

/**
 * This is the model base class for the table "tb_cliente".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbCliente".
 *
 * Columns in table "tb_cliente" available as properties of the model,
 * followed by relations of table "tb_cliente" available as properties of the model.
 *
 * @property integer $id_cliente
 * @property string $Nombre_Comercial
 * @property string $Cliente
 * @property string $Telefono
 * @property string $Provincia
 * @property string $Ciudad
 * @property string $Dirección
 * @property string $email
 *
 * @property TbPedido[] $tbPedidos
 */
abstract class BaseTbCliente extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tb_cliente';
    }

    public static function representingColumn() {
        return 'Nombre_Comercial';
    }

    public function rules() {
        return array(
            array('Nombre_Comercial, Cliente, Dirección', 'length', 'max'=>75),
            array('Telefono', 'length', 'max'=>15),
            array('Provincia, Ciudad', 'length', 'max'=>50),
            array('email', 'length', 'max'=>45),
            array('Nombre_Comercial, Cliente, Telefono, Provincia, Ciudad, Dirección, email', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_cliente, Nombre_Comercial, Cliente, Telefono, Provincia, Ciudad, Dirección, email', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'tbPedidos' => array(self::HAS_MANY, 'TbPedido', 'id_Cliente'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_cliente' => Yii::t('app', 'Id Cliente'),
                'Nombre_Comercial' => Yii::t('app', 'Nombre Comercial'),
                'Cliente' => Yii::t('app', 'Cliente'),
                'Telefono' => Yii::t('app', 'Telefono'),
                'Provincia' => Yii::t('app', 'Provincia'),
                'Ciudad' => Yii::t('app', 'Ciudad'),
                'Dirección' => Yii::t('app', 'Dirección'),
                'email' => Yii::t('app', 'Email'),
                'tbPedidos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_cliente', $this->id_cliente);
        $criteria->compare('Nombre_Comercial', $this->Nombre_Comercial, true);
        $criteria->compare('Cliente', $this->Cliente, true);
        $criteria->compare('Telefono', $this->Telefono, true);
        $criteria->compare('Provincia', $this->Provincia, true);
        $criteria->compare('Ciudad', $this->Ciudad, true);
        $criteria->compare('Dirección', $this->Dirección, true);
        $criteria->compare('email', $this->email, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}